name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Display directory structure
        run: find . -maxdepth 3 -type d

      - name: Display tsconfig.json
        run: cat tsconfig.json

      - name: Setup Firebase Config
        run: cp configs/firebaseConfig.template.ts configs/firebaseConfig.ts

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm test
